# This workflow was created just to teach how to configure it.

name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest

    strategy:
      matrix:
        solution: [ '/src/Aula01/CarrinhoCompras.sln', '/src/Aula02/TDDExample.sln', '/src/Aula05/MoqSample.sln']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Restore dependencies
    - name: Restore
      run: dotnet restore ${{ matrix.solution }}
      
    - name: Build
      run: dotnet build ${{ matrix.solution }} --configuration Release --no-restore

    # Execute all unit tests in the solution
    - name: Test
      run: dotnet test ${{ matrix.solution }} --configuration Release --no-build --verbosity normal
