# This workflow was created just to teach how to configure it.

name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        solution: [ './src/Aula05/TestIntegracao/TestIntegracao.sln']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore ${{ matrix.solution }}        

    # - name: Find and Build All Solutions
    #   run: |
    #     for sln in $(find . -name '*.sln'); do
    #       echo "🔧 Building and testing $sln"
    #       dotnet restore "$sln"
    #       dotnet build "$sln" --configuration Release --no-restore
    #       dotnet test "$sln" --configuration Release --no-build --verbosity normal
    #     done